'use strict';
const $=id=>document.getElementById(id);
let current=null,baseline=null,active='Claims',filter='',selectedId=null;
const kinds={Claims:'claims',Timeline:'events',Relations:'relations',Challenge:'hypotheses',Sources:'sources',Delta:null};
const groups=['sources','captures','observations','claims','events','entities','relations','inferences','hypotheses','contradictions','assessments','recommendations','decisions','outcomes','artifacts','checks','blockers','history'];
function el(tag,text,attrs={}){const n=document.createElement(tag);if(text!=null)n.textContent=text;for(const [k,v] of Object.entries(attrs))n.setAttribute(k,v);return n;}
function add(p,...nodes){nodes.flat().filter(Boolean).forEach(n=>p.append(n));return p;}
function button(text,fn){const b=el('button',text,{type:'button'});b.onclick=fn;return b;}
function valid(c){if(c.format!=='cd-observatory-case/v1'||!c.case_id||!c.question)throw Error('Expected a named cd-observatory-case/v1 with question');const ids=new Set();for(const k of groups){if(!Array.isArray(c[k]))throw Error('Missing typed object array '+k);for(const o of c[k]){if(!o.id)throw Error('Object without ID in '+k);if(ids.has(o.id))throw Error('Duplicate object ID '+o.id);ids.add(o.id);}}return c;}
async function load(f,base=false){if(!f)return;try{if(f.size>5e6)throw Error('Case exceeds 5 MB');const c=valid(JSON.parse(await f.text()));if(base)baseline=c;else current=c;selectedId=null;render();$('status').textContent=(base?'Baseline':'Current case')+' loaded as dated read-only evidence. No background monitoring or write.';}catch(e){$('status').textContent='Rejected case; previous selection retained. '+e.message;}}
function value(v){return typeof v==='object'?JSON.stringify(v,null,2):String(v??'Not recorded');}
function title(o){return o.title||o.statement||o.summary||o.name||o.description||o.id;}
function references(o){return [...new Set(Object.entries(o).filter(([k])=>k.endsWith('_ids')).flatMap(([,v])=>Array.isArray(v)?v:[]))];}
function find(id){for(const k of groups){const o=current[k].find(o=>o.id===id);if(o)return{k,o};}return null;}
function objectCard(kind,o){const card=el('article',null,{class:'card object-proof'});add(card,el('p',kind+' · '+o.id,{class:'eyebrow'}),el('h3',title(o)),el('span',o.status??'Status not recorded',{class:'badge'}),el('span','Confidence: '+value(o.confidence??'not recorded'),{class:'badge'}),el('p','Uncertainty: '+value(o.uncertainty??'not recorded')));
 for(const k of ['description','summary','statement','body','reason','event_start','event_end','observed_at','published_at','retrieved_at','first_seen_at','last_seen_at','relation_type','from_id','to_id'])if(o[k]!==undefined&&value(o[k])!==title(o))add(card,el('h4',k.replaceAll('_',' ')),el('p',value(o[k]),{class:'native-text'}));
 const links=el('div',null,{class:'reference-actions'});for(const id of references(o))links.append(button('Inspect '+id,()=>inspect(id)));if(kind==='relations'){links.append(button('Origin '+o.from_id,()=>inspect(o.from_id)),button('Target '+o.to_id,()=>inspect(o.to_id)));}card.append(links);
 const details=el('details');add(details,el('summary','All original fields · preserved'),el('pre',JSON.stringify(o,null,2)));card.append(details);return card;}
function inspect(id){const found=find(id),pane=$('evidence-pane');if(!found){$('status').textContent='Unresolved native reference: '+id;pane?.replaceChildren(el('p','Native reference not found: '+id,{class:'notice'}));return;}if(!pane){const d=$('editor');$('editor-content').replaceChildren(objectCard(found.k,found.o),button('Close evidence',()=>d.close()));d.showModal();return;}pane.replaceChildren(el('h3','Exact referenced record'),objectCard(found.k,found.o));pane.setAttribute('tabindex','-1');pane.focus({preventScroll:true});}
function visible(){const keys=active==='Challenge'?['hypotheses','contradictions','assessments','blockers']:active==='Sources'?['sources','captures']:active==='Relations'?['entities','relations']:active==='Timeline'?['events','observations']:[kinds[active]];let rows=keys.flatMap(k=>current[k].map(o=>({k,o})));if(active==='Timeline')rows=rows.slice().sort((a,b)=>String(a.o.event_start||a.o.observed_at||'~').localeCompare(String(b.o.event_start||b.o.observed_at||'~')));return rows;}
function list(rows){const target=$('object-list');target.replaceChildren();for(const {k,o} of rows.filter(({o})=>JSON.stringify(o).toLowerCase().includes(filter.toLowerCase()))){const b=button('',()=>{selectedId=o.id;read(rows);list(rows);});b.setAttribute('aria-current',selectedId===o.id?'page':'false');add(b,el('small',k+' · '+o.id),el('strong',title(o)),el('span',active==='Timeline'?value(o.event_start||o.observed_at||'Time not recorded'):value(o.status||'State not recorded')));target.append(b);}if(!target.children.length)target.append(el('p','No matching native objects.'));}
function read(rows){const selected=rows.find(r=>r.o.id===selectedId)||rows[0];if(!selected){$('record-pane').replaceChildren(el('p','No native object in this projection.',{class:'empty'}));return;}selectedId=selected.o.id;$('record-pane').replaceChildren(objectCard(selected.k,selected.o));const refs=references(selected.o),linked=current.contradictions.filter(o=>references(o).includes(selectedId));const pane=$('evidence-pane');pane.replaceChildren(el('h3','Provenance & challenge'));
 for(const id of refs){const found=find(id);pane.append(found?objectCard(found.k,found.o):el('p','Unresolved native reference: '+id,{class:'notice'}));}for(const o of linked)if(!refs.includes(o.id))pane.append(objectCard('contradictions',o));if(!refs.length&&!linked.length)pane.append(el('p','No exact provenance/challenge reference recorded for this object. No relation inferred.'));}
function changes(){const rows=[];if(!baseline)return rows;for(const k of groups){const old=new Map(baseline[k].map(o=>[o.id,o])),now=new Map(current[k].map(o=>[o.id,o]));for(const [id,o] of now){const prior=old.get(id);if(!prior||JSON.stringify(prior)!==JSON.stringify(o))rows.push({k,id,state:prior?'CHANGED':'NEW',prior,current:o});}for(const [id,o] of old)if(!now.has(id))rows.push({k,id,state:'NO LONGER REPRESENTED',prior:o,current:null});}return rows;}
function relationLanes(){const section=el('section',null,{class:'relation-lanes'});section.append(el('h3','Recorded entity-relation lanes · not inferred links'));for(const r of current.relations){const lane=el('div',null,{class:'relation-lane'});const origin=find(r.from_id),target=find(r.to_id);add(lane,button(origin?title(origin.o):'Unresolved '+r.from_id,()=>inspect(r.from_id)),el('span',(r.relation_type||'Untyped')+' → '+(r.status||'State not recorded')),button(target?title(target.o):'Unresolved '+r.to_id,()=>inspect(r.to_id)),button('Inspect '+r.id,()=>inspect(r.id)));section.append(lane);}if(!current.relations.length)section.append(el('p','No native relationship recorded.'));return section;}
function delta(m){m.append(el('p','Structural ID comparison, not reviewed material change. Baseline '+(baseline?.case_id||'not selected')+' / current '+current.case_id+'. Different case IDs are not merged.',{class:'notice'}));if(!baseline){m.append(el('p','Select a baseline JSON to compare exact retained objects.'));return;}for(const d of changes()){const section=el('section',null,{class:'delta-proof'});add(section,el('h3',d.state+' · '+d.k+' · '+d.id));const pair=el('div',null,{class:'delta-pair'});add(pair,add(el('section'),el('p','Baseline',{class:'eyebrow'}),d.prior?objectCard(d.k,d.prior):el('p','Not represented in baseline')),add(el('section'),el('p','Current',{class:'eyebrow'}),d.current?objectCard(d.k,d.current):el('p','No longer represented in current case')));section.append(pair);m.append(section);}if(!changes().length)m.append(el('p','No typed object differences found.'));}
function render(){const m=$('main');m.replaceChildren();document.querySelectorAll('#nav button').forEach(b=>b.setAttribute('aria-current',b.textContent===active?'page':'false'));if(!current){m.append(el('p','Select a native case JSON or load the explicitly synthetic Harbor Lantern case. Nothing is collected or preloaded.',{class:'empty'}));return;}
 const head=el('section',null,{class:'case-question'});add(head,el('p',current.case_id+' · '+current.phase+' · '+current.posture,{class:'eyebrow'}),el('h2',current.title),el('p',current.question,{class:'question-text'}),el('p','Audience: '+value(current.audience_or_decision)+' · Horizon: '+value(current.time_horizon)),el('p','Next recorded move: '+value(current.next_action?.action)+' · '+value(current.next_action?.owner)));const limits=el('details');add(limits,el('summary','Collection authority & harm boundary'),el('p',value(current.collection_authority)),el('p',value(current.harm_model)));head.append(limits);m.append(head);if(active==='Delta'){delta(m);return;}
 const room=el('section',null,{class:'case-atlas'}),index=el('aside',null,{class:'case-index'}),search=el('input',null,{id:'filter',type:'search',placeholder:'Search this native projection'});search.value=filter;add(index,el('h3',active+' index'),el('label','Find retained object',{for:'filter'}),search,el('nav',null,{id:'object-list','aria-label':'Native case objects'}));add(room,index,el('section',null,{id:'record-pane'}),el('aside',null,{id:'evidence-pane',class:'evidence-pane'}));m.append(room);if(active==='Relations')m.append(relationLanes());const rows=visible();if(!rows.some(r=>r.o.id===selectedId))selectedId=rows[0]?.o.id;list(rows);read(rows);search.oninput=()=>{filter=search.value;list(rows);};}
$('case').onchange=e=>load(e.target.files[0]);$('baseline').onchange=e=>load(e.target.files[0],true);$('sample').onclick=()=>{current=valid(structuredClone(OBS_SAMPLE.current));baseline=valid(structuredClone(OBS_SAMPLE.baseline));filter='';selectedId=null;render();$('status').textContent='SYNTHETIC Harbor Lantern · dated fixture only, not a live feed or verified case.';};$('clear').onclick=()=>{current=null;baseline=null;filter='';selectedId=null;render();$('status').textContent='Private case data cleared from memory.';};Object.keys(kinds).forEach(k=>$('nav').append(button(k,()=>{active=k;filter='';selectedId=null;render();})));$('skin').onchange=e=>document.body.dataset.skin=e.target.value;render();
