"use strict";
const $=s=>document.querySelector(s), esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const token=new URLSearchParams(location.hash.slice(1)).get("session");history.replaceState({mode:"collections"},"",location.pathname);
let catalogRevision=-1,catalogPollBusy=false,catalogRefreshReady=false,catalog=[],state={mode:"collections"},serial=0,controller=null,data=null,current=null,selection=[],filter="",counts={};
const names={collections:"Collections",notes:"Saved notes",pins:"Reminders",people:"People"};
function status(v,error=false){$("#status").textContent=v;$("#status").classList.toggle("error",error)}
async function api(action,body={},signal){const r=await fetch("/api/read",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,...body}),cache:"no-store",signal});const value=await r.json();if(!r.ok||value.error)throw Error(value.error||"This content could not be opened.");return value}
const collectionCopy={
 'scrapbook':'Images, themes, labels, and designs we made. Reuse a look or build on earlier work.',
 'rpg-library':'Characters, settings, adventures, and illustrations for our games.',
 'our-wiki':'Ideas, explanations, questions, and notes in our shared notebook.',
 'personal-ai-archive':'Previous conversations, generated images, and saved reference material.',
 'research-library':'Papers and reference books for reading and research.',
 'recipes':'Recipes, variations, printable kitchen sheets, and cooking notes.',
 'archive-loom':'Saved videos, transcripts, and connected notes.',
 'retained-packets':'Saved research extracts and knowledge material to read and reuse.'};
function sectionName(s,x){if(s.id==='personal-ai-archive'){return {'Source & retention policy':'About this archive','Searchable archive stores':'Conversations & documents'}[x.title]||x.title}return x.title}
function store(){return catalog.find(x=>x.id===state.id)}
function displayName(path){return path.split("/").pop().replace(/^ab-food-\d+-/i,"").replace(/\.(md|txt|pdf|docx|png|jpg|jpeg|gif|webp)$/i,"").replace(/[_-]/g," ")}
function button(text,attrs="",cls=""){return '<button type="button" class="'+cls+'" '+attrs+'>'+esc(text)+'</button>'}
function sourceDetails(value){return '<details class="source-details"><summary>Source details</summary><pre>'+esc(JSON.stringify(value,null,2))+'</pre></details>'}
function heading(){const s=store();$("#heading").textContent=s?s.name:state.mode==="collections"?"Your knowledge, ready to open.":names[state.mode];$("#description").textContent=s?(collectionCopy[s.id]||s.summary):({collections:"Open a collection, browse its contents, and use what you find with Nova.",notes:"The thoughts, questions, and source material we saved. Your private notes are included.",pins:"The things we wanted to remember, across our projects.",people:"People we have saved information about. Open a name to read it."})[state.mode];document.querySelectorAll("[data-mode]").forEach(b=>b.setAttribute("aria-current",b.dataset.mode===state.mode?"page":"false"));$("#crumbs").innerHTML=s?button("← All collections",'data-home')+(state.path||state.folder?button("↑ Back to folder",'data-up'):""):"";$("#search-toggle").textContent=state.mode==="collection"?"Find in this folder…":"Search…";$("#search-help").textContent=state.mode==="collection"?"Filters the file names in the open folder. Browse its pages to see more.":state.mode==="archive"?"Searches the archived conversation text. Leave it blank to browse titles.":"Filters the contents already shown. You can browse without entering anything.";$("#search-panel").hidden=true;$("#search-toggle").setAttribute("aria-expanded","false");$("#query").value=""}
async function navigate(next,push=true){state={...next};if(push)history.pushState(state,"",location.pathname);filter="";current=null;data=null;const n=++serial;controller?.abort();controller=new AbortController();heading();$("#results").setAttribute("aria-busy","true");$("#results").innerHTML='<section class="empty"><h3>Opening '+esc(store()?.name||names[state.mode]||"contents")+'…</h3></section>';status("Opening contents…");try{
 if(state.mode==="collections"){if(!catalog.length)catalog=(await api("catalog",{},controller.signal)).stores;if(n!==serial)return;renderHome();loadCounts(n)}
 else if(["notes","pins","people"].includes(state.mode)){const value=await api(state.mode,state.mode==="pins"?{all_projects:true}:{},controller.signal);if(n!==serial)return;if(value.exit_code!==0)throw Error(value.native?.message||value.native?.reason||value.native?.diagnostic||"This saved content could not be read.");data=value;renderRecords()}
 else if(state.mode==="archive"){data=await api(state.document?"archive-parts":"archive-documents",{id:state.id,offset:state.offset||0,...state.document,snapshot:state.snapshot},controller.signal);if(n!==serial)return;renderArchive()}
 else{const [listing,preview]=await Promise.all([api("browse",{id:state.id,path:state.folder||"",offset:state.offset||0},controller.signal),state.path?api("preview",{id:state.id,path:state.path,offset:state.textOffset||0,page:state.page||0},controller.signal):Promise.resolve(null)]);if(n!==serial)return;data=listing;renderCollection(preview)}
 if(n===serial){$("#results").setAttribute("aria-busy","false");status("Ready to browse.")}
 }catch(e){if(e.name==="AbortError"||n!==serial)return;$("#results").setAttribute("aria-busy","false");$("#results").innerHTML='<section class="empty"><h3>Couldn’t open this content</h3><p>'+esc(e.message)+'</p>'+button("Try again",'data-retry')+'</section>';status(e.message,true)}}
function renderHome(){heading();$("#results").innerHTML='<div class="quick-shelves">'+["notes","pins","people"].map(m=>'<button type="button" data-mode="'+m+'"><strong>'+names[m]+'</strong><span id="count-'+m+'">Open and browse →</span></button>').join("")+'</div><div class="section-heading"><h3>Our collections</h3><span>'+catalog.length+' collections</span></div><div class="collection-grid">'+catalog.map(s=>'<section class="collection-card" data-card="'+esc(s.id)+'"><div class="book-top"><span class="book-mark" aria-hidden="true">'+({"scrapbook":"✦","rpg-library":"♜","our-wiki":"✎","recipes":"♨","personal-ai-archive":"◷","research-library":"⌘","archive-loom":"▤","retained-packets":"▧"}[s.id]||"▤")+'</span><span>'+esc(s.topics?.slice(0,2).join(" · ")||"Collection")+'</span></div><h4>'+esc(s.name)+'</h4><p>'+esc(collectionCopy[s.id]||s.summary||s.use_when?.[0]||"Open this collection to explore its contents.")+'</p><div class="section-links">'+s.sections.slice(0,3).map(x=>button(sectionName(s,x),'data-store="'+esc(s.id)+'" data-section="'+esc(x.path)+'"')).join("")+'</div>'+button(s.available?"Open collection →":"Check collection →",'data-store="'+esc(s.id)+'"',"open-collection")+(!s.available?'<p class="small">This location is currently unavailable.</p>':"")+'</section>').join("")+'</div><p class="home-note">Choose a collection or open saved notes, reminders, or people. Search is there when you want a shortcut.</p>';applyFilter()}
async function loadCounts(n){await Promise.all(["notes","pins","people"].map(async m=>{try{const r=await api(m,m==="pins"?{all_projects:true}:{});if(r.exit_code!==0)return;const rows=objects(r.native);counts[m]=m==="people"?new Set(rows.map(x=>x.person_id)).size:rows.length;if(n===serial&&$("#count-"+m))$("#count-"+m).textContent=counts[m]+(m==="people"?(counts[m]===1?" person":" people"):m==="pins"?" reminders":" saved entries")+" · Open →"}catch{}}))}
function objects(n){if(Array.isArray(n))return n;for(const k of ["records","pins","hits","results"])if(Array.isArray(n?.[k]))return n[k];return []}
function title(r){return r.title||r.display_name||r.name||r.text?.split(/\n|(?<=[.!?]) /)[0]?.slice(0,100)||"Saved entry"}
function body(r){return r.body||r.text||r.snippet||r.retrieval_text||r.cue||""}
function snippet(r){return String(body(r)).replace(/[#*_\x60]/g,"").replace(/\s+/g," ").slice(0,145)}
function recordRows(){const rows=objects(data.native);if(state.mode!=="people")return rows;const grouped=new Map();for(const r of rows){const id=r.person_id||"Unnamed person";if(!grouped.has(id))grouped.set(id,{id,title:r.person_name||id.replace(/^person[.-]/,"").split(/[-_.]/).map(x=>x[0]?.toUpperCase()+x.slice(1)).join(" "),parts:[]});grouped.get(id).parts.push(r)}return [...grouped.values()]}
function renderRecords(index=0){const rows=recordRows();$("#results").innerHTML='<div class="browse-work"><section class="contents-pane"><h3>'+rows.length+' '+(state.mode==="people"?"people":state.mode==="pins"?"reminders":"saved entries")+'</h3><div class="content-list">'+rows.map((r,i)=>'<button type="button" data-record="'+i+'" data-filter="'+esc(title(r)+" "+snippet(r))+'" '+(i===index?'aria-current="page"':"")+'><strong>'+esc(title(r))+'</strong><span>'+esc(state.mode==="people"?r.parts.length+" saved details":snippet(r))+'</span></button>').join("")+'</div></section><article id="reader" class="reader" tabindex="-1"></article></div>';if(!rows.length){$("#reader").innerHTML='<h3>Nothing saved here yet.</h3><p>When we save something here, it will appear in this view.</p>';return}const r=rows[index];current={title:title(r),text:state.mode==="people"?r.parts.map(x=>x.text).join("\n\n"):body(r),source:names[state.mode],path:r.id||r.person_id||r.parts?.[0]?.person_id||"",native:r};renderReader(current.text,current.title);const linked=linkedCollection(r);if(linked)$("#reader .reading-actions").insertAdjacentHTML("beforeend",button("Open "+linked.name+" →",'data-store="'+esc(linked.id)+'"'));applyFilter()}
function folderOf(path){return path.includes("/")?path.slice(0,path.lastIndexOf("/")):""}
function pages(offset,next,total,kind){if(!offset&&next==null)return "";return '<div class="pagination">'+(offset?button("← Previous",'data-page="'+Math.max(0,offset-(kind==="archive"?40:200))+'"'):"")+'<span>'+esc(offset+1)+'–'+esc(Math.min(total,offset+(kind==="archive"?40:200)))+' of '+esc(total)+'</span>'+(next!=null?button("Next →",'data-page="'+next+'"'):"")+'</div>'}
function renderCollection(preview){const s=store(),overview=data.overview,read=preview||overview?.index;const shortcuts=s.sections.map(x=>button(sectionName(s,x),'data-section="'+esc(x.path)+'" data-store="'+esc(s.id)+'"')).join("");$("#results").innerHTML='<div class="browse-work"><section class="contents-pane">'+(shortcuts?'<details class="named-sections" open><summary>In this collection</summary>'+shortcuts+'</details>':"")+button("Collection start",'data-root',"folder-home")+'<h3>'+esc(state.folder?displayName(state.folder):"Folders & files")+'</h3>'+pages(data.offset||0,data.next_offset,data.total||data.entries.length,"folder")+'<div class="content-list">'+data.entries.map(x=>'<button type="button" data-path="'+esc(x.path)+'" data-directory="'+x.directory+'" data-filter="'+esc(x.name)+'" '+(x.linked?'disabled title="Linked locations require their own registered collection"':"")+'><strong><span aria-hidden="true">'+(x.directory?"▸ ":"· ")+'</span>'+esc(displayName(x.name))+'</strong><span>'+esc(x.directory?"Folder":x.name.split(".").pop().toUpperCase())+'</span></button>').join("")+'</div>'+(!data.entries.length?'<p class="small">No visible files in this folder.</p>':"")+pages(data.offset||0,data.next_offset,data.total||data.entries.length,"folder")+'</section><article id="reader" class="reader" tabindex="-1"></article></div>';if(overview?.archive&&!state.path){$("#reader").innerHTML='<p class="overline">Saved conversations & documents</p><h3>'+esc(s.name)+'</h3><p>'+esc(overview.archive.document_count)+' saved conversations and documents are available. Browse their titles, open one, and read its messages in order.</p>'+button("Browse conversations →",'data-archive',"primary")+(read?'<div class="reader-body">'+rich(read.text,read.path)+'</div>':"");current=null}else if(read){renderPreview(read)}else{$("#reader").innerHTML='<p class="overline">'+esc(s.name)+'</p><h3>'+esc(state.folder?displayName(state.folder):"Open a folder or document")+'</h3><p>'+esc(overview?.status==="missing"?"This collection’s registered folder cannot be found.":"Choose something from the contents beside this page.")+'</p>';current=null}applyFilter()}
function actionBar(){return '<div class="reading-actions">'+button("Add to working set",'data-collect',"primary")+button("Copy text",'data-copy')+'</div>'}
function renderReader(text,titleText,path=""){const el=$("#reader");el.innerHTML='<p class="overline">'+esc(current.source)+'</p><h3>'+esc(titleText)+'</h3>'+actionBar()+'<div class="reader-body">'+rich(text,path)+'</div>'+sourceDetails(current.native)}
function renderPreview(read){current={title:read.text?.match(/^#\s+([^\r\n]+)/m)?.[1]?.trim()||displayName(read.path)||store().name,text:read.text,source:store().name,path:read.path,native:read,storeId:state.id};if(read.format==="image"){$("#reader").innerHTML='<p class="overline">'+esc(current.source)+'</p><h3>'+esc(current.title)+'</h3>'+button("Add to working set",'data-collect',"primary")+'<figure><img class="source-image" src="'+esc(read.media_url)+'" alt="'+esc(current.title)+'"></figure>'+sourceDetails(read)}else{renderReader(read.text,current.title,read.path);if(read.format==="pdf"||read.format==="docx")$("#reader .reader-body").innerHTML='<p class="reading-note">'+(read.format==="pdf"?"PDF text · images and page layout are available in the original PDF.":"Document text · images and layout are available in the original document.")+'</p><pre class="document-text">'+esc(read.text||"No readable text on these pages.")+'</pre>';if(read.next_offset!=null||read.next_page!=null)$("#reader").insertAdjacentHTML("beforeend",'<div class="continue-reading">'+(read.next_offset!=null?button("Read next part →",'data-text-offset="'+read.next_offset+'"'):button("Next pages →",'data-pdf-page="'+read.next_page+'"'))+'</div>')}
 if(state.anchor){const hit=[...$("#reader").querySelectorAll("h3,h4,h5,h6")].find(x=>x.id===state.anchor.toLowerCase());hit?.scrollIntoView({block:"start"})}}
function renderArchive(){const isDoc=!!state.document,rows=isDoc?data.hits:data.documents;$("#results").innerHTML='<div class="browse-work"><section class="contents-pane">'+(isDoc?button("← Conversation titles",'data-archive-root'):"")+'<h3>'+esc(isDoc?data.title||"Matching messages":"Saved conversations & documents")+'</h3><p class="small">'+data.total+' '+(isDoc?"messages / parts":"titles")+'</p>'+pages(data.offset||0,data.next_offset,data.total,"archive")+'<div class="content-list">'+rows.map((r,i)=>'<button type="button" '+(isDoc?'data-archive-part="'+i+'"':'data-document="'+i+'"')+' data-filter="'+esc(r.title+" "+(r.snippet||""))+'"><strong>'+esc(isDoc?(r.role||"Part")+" · "+(r.locator.ordinal+1):r.title||"Untitled conversation")+'</strong><span>'+esc(isDoc?r.snippet:r.part_count+" messages / parts")+'</span></button>').join("")+'</div>'+pages(data.offset||0,data.next_offset,data.total,"archive")+'</section><article id="reader" class="reader" tabindex="-1"><p class="overline">'+esc(store().name)+'</p><h3>'+esc(isDoc?"Read this conversation":"Open a saved conversation")+'</h3><p>'+esc(isDoc?"Choose a message or part on the left to read it.":"Browse the titles beside this page. Open one to see its messages in order.")+'</p></article></div>';applyFilter()}
async function openArchivePart(anchor){const n=serial;try{const read=await api("archive-record",{id:state.id,...anchor},controller.signal);if(n!==serial)return;current={title:read.title||"Saved conversation",text:read.text,source:store().name,path:read.path,native:read,storeId:state.id};renderReader(read.text,(read.role||"Message")+" · "+current.title);if(read.next_offset!=null)$("#reader").insertAdjacentHTML("beforeend",button("Read next part →",'data-archive-next="'+read.next_offset+'"'));$("#reader").focus({preventScroll:true});status("Message opened.")}catch(e){if(e.name!=="AbortError")status(e.message,true)}}


function linkedCollection(record){const text=JSON.stringify(record).replace(/\\+/g,"/").toLowerCase();return catalog.find(s=>text.includes(s.location.replaceAll("\\","/").toLowerCase()))}
function resolveLink(raw,base){let target;try{target=decodeURIComponent(raw.replace(/^<|>$/g,"").split("#")[0])}catch{return null}if(!target)return null;if(/^[a-z][a-z0-9+.-]*:/i.test(target)||target.startsWith("/"))return null;const parts=folderOf(base).split("/").filter(Boolean);for(const part of target.replaceAll("\\","/").split("/")){if(part===".."){if(!parts.length)return null;parts.pop()}else if(part&&part!==".")parts.push(part)}return parts.join("/")}
function absoluteLink(raw){let target;try{target=decodeURIComponent(raw.replace(/^<|>$/g,"").split("#")[0]).replaceAll("\\","/")}catch{return null}if(!/^[a-z]:\//i.test(target))return null;for(const entry of catalog){const root=entry.location.replaceAll("\\","/").replace(/\/$/,"");if(target.toLowerCase()===root.toLowerCase()||target.toLowerCase().startsWith(root.toLowerCase()+"/"))return {id:entry.id,path:target.slice(root.length).replace(/^\//,"")}}return null}
function inline(raw,base){const slots=[];function put(html){slots.push(html);return "\u0001"+(slots.length-1)+"\u0001"}let line=String(raw).replace(/!?\[([^\]]+)\]\(([^)]+)\)/g,(full,label,url)=>{if(full.startsWith("!")){const path=resolveLink(url,base);return put(path?'<a href="#" data-link="'+esc(path)+'">View image: '+esc(label)+'</a>':esc(label))}const cross=absoluteLink(url);if(cross)return put('<a href="#" data-cross-store="'+esc(cross.id)+'" data-link="'+esc(cross.path)+'">'+esc(label)+'</a>');if(/^https?:\/\//i.test(url))return put('<a href="'+esc(url)+'" target="_blank" rel="noreferrer">'+esc(label)+'</a>');const path=resolveLink(url,base);return put(path?'<a href="#" data-link="'+esc(path)+'" data-anchor="'+esc(url.split("#")[1]||"")+'">'+esc(label)+'</a>':esc(label))}).replace(/\[\[([^\]|]+)(?:\|([^\]]+))?\]\]/g,(_,path,label)=>put('<a href="#" data-link="'+esc(path.endsWith(".md")?path:path+".md")+'">'+esc(label||path)+'</a>'));line=esc(line).replace(/\*\*([^*]+)\*\*/g,"<strong>$1</strong>").replace(/\x60([^\x60]+)\x60/g,"<code>$1</code>");return line.replace(/\u0001(\d+)\u0001/g,(_,i)=>slots[Number(i)])}
function slug(v){return v.toLowerCase().replace(/[^\p{L}\p{N}\s-]/gu,"").trim().replace(/\s+/g,"-")}
function rich(text,base=""){let lines=String(text||"").split(/\r?\n/),out="",list=false,code=false,table=false;function close(){if(list){out+="</ul>";list=false}if(table){out+="</tbody></table></div>";table=false}}if(lines[0]==="---"){const end=lines.indexOf("---",1);if(end>=0)lines=lines.slice(end+1)}for(let i=0;i<lines.length;i++){const line=lines[i];const sourceAnchor=line.match(/^<a id="([a-zA-Z0-9_-]+)"><\/a>$/);if(sourceAnchor){close();out+='<span id="'+esc(sourceAnchor[1])+'"></span>';continue}if(line.startsWith("\x60\x60\x60")){close();out+=code?"</code></pre>":'<pre class="document-text"><code>';code=!code;continue}if(code){out+=esc(line)+"\n";continue}if(/^\|/.test(line)){if(/^\|[\s:|-]+\|\s*$/.test(line))continue;if(list){out+="</ul>";list=false}if(!table){out+='<div class="table-scroll"><table><tbody>';table=true}out+="<tr>"+line.replace(/^\||\|$/g,"").split("|").map(x=>"<td>"+inline(x.trim(),base)+"</td>").join("")+"</tr>";continue}if(table){out+="</tbody></table></div>";table=false}if(/^[-*] /.test(line)){if(!list){out+="<ul>";list=true}out+="<li>"+inline(line.slice(2),base)+"</li>";continue}if(list){out+="</ul>";list=false}const h=line.match(/^(#{1,6}) (.*)$/);if(h){const level=Math.min(6,h[1].length+2);out+='<h'+level+' id="'+esc(slug(h[2]))+'">'+inline(h[2],base)+"</h"+level+">"}else if(line.startsWith("> "))out+="<blockquote>"+inline(line.slice(2),base)+"</blockquote>";else if(line.trim())out+="<p>"+inline(line,base)+"</p>"}close();if(code)out+="</code></pre>";return out}
function applyFilter(){let visible=0;document.querySelectorAll("[data-filter],[data-card]").forEach(el=>{const text=el.dataset.filter||el.textContent;el.hidden=!!filter&&!text.toLowerCase().includes(filter);if(!el.hidden)visible++});$("#filter-empty")?.remove();if(filter&&!visible)$("#results").insertAdjacentHTML("afterbegin",'<p id="filter-empty">No match in this view. Clear search to keep browsing.</p>')}
async function copy(text){try{await navigator.clipboard.writeText(text);return true}catch{const box=document.createElement("textarea");box.value=text;document.body.append(box);box.select();const done=document.execCommand("copy");box.remove();return done}}
function collect(){if(!current)return;const selected=window.getSelection();const excerpt=selected&&!selected.isCollapsed&&$("#reader").contains(selected.anchorNode)&&$("#reader").contains(selected.focusNode)?selected.toString():"";const item={...current,location:current.storeId?catalog.find(s=>s.id===current.storeId)?.location||"":"",collectedAt:new Date().toISOString(),text:excerpt||current.text};const key=current.source+"|"+current.path+"|"+(current.native.sample_sha256||JSON.stringify(current.native))+"|"+item.text;if(selection.some(x=>x.key===key)){status("Already in your working set.");return}selection.push({...item,key});$("#working-count").textContent=selection.length;status('Added “'+current.title+'” to your working set.')}
function renderWorking(){$("#working-items").innerHTML=selection.length?selection.map((s,i)=>'<div class="working-item"><div><strong>'+esc(s.title)+'</strong><p>'+esc(s.source)+'</p></div>'+button("Remove",'data-remove="'+i+'"')+'</div>').join(""):'<p>Open a page, note, reminder, or image and choose <strong>Add to working set</strong>.</p>';$("#copy-request").disabled=!selection.length;$("#save-packet").disabled=!selection.length}
document.addEventListener("click",async e=>{const b=e.target.closest("button,a[data-link]");if(!b)return;const d=b.dataset;
 if(d.mode){navigate({mode:d.mode});return}if("home" in d){navigate({mode:"collections"});return}if("retry" in d){navigate(state,false);return}
 if(d.store){const target=d.section||"";if(d.store==="personal-ai-archive"&&target==="rag"){navigate({mode:"archive",id:d.store});return}try{const place=target?await api("locate",{id:d.store,path:target}):{directory:true};navigate({mode:"collection",id:d.store,folder:place.directory?target:folderOf(target),path:place.directory?"":target})}catch(err){status(err.message,true)}return}
 if("up" in d){navigate({mode:"collection",id:state.id,folder:state.path?state.folder:folderOf(state.folder||"")});return}if("root" in d){navigate({mode:"collection",id:state.id});return}
 if(d.path){navigate({mode:"collection",id:state.id,folder:d.directory==="true"?d.path:folderOf(d.path),path:d.directory==="true"?"":d.path});return}
 if(d.link){e.preventDefault();navigate({mode:"collection",id:d.crossStore||state.id,folder:folderOf(d.link),path:d.link,anchor:d.anchor});return}
 if(d.record!=null){renderRecords(Number(d.record));$("#reader").focus({preventScroll:true});return}
 if("archive" in d||"archiveRoot" in d){navigate({mode:"archive",id:state.id});return}
 if(d.document!=null){const row=data.documents[Number(d.document)];navigate({mode:"archive",id:state.id,document:{source:row.source,external_id:row.external_id},snapshot:data.snapshot});return}
 if(d.archivePart!=null){openArchivePart(data.hits[Number(d.archivePart)].anchor);return}
 if(d.archiveNext!=null){openArchivePart({...current.native.anchor,offset:Number(d.archiveNext)});return}
 if(d.page!=null){navigate({...state,offset:Number(d.page),snapshot:data.snapshot});return}
 if(d.textOffset!=null){navigate({...state,path:current.path,textOffset:Number(d.textOffset)});return}if(d.pdfPage!=null){navigate({...state,path:current.path,page:Number(d.pdfPage),textOffset:0});return}
 if("collect" in d){collect();return}if("copy" in d){status(await copy(current.text)?"Text copied. Paste it where you want to use it.":"Copy unavailable in this browser.");return}
 if(d.remove!=null){selection.splice(Number(d.remove),1);$("#working-count").textContent=selection.length;renderWorking()}
});
$("#skin").onchange=e=>document.body.dataset.skin=e.target.value;
async function refreshCatalog(automatic=false){if(catalogPollBusy||automatic&&(!catalogRefreshReady||document.hidden))return;catalogPollBusy=true;try{if(automatic){const stamp=await api("catalog-status");if(stamp.revision===catalogRevision)return}const value=await api("catalog");catalog=value.stores;catalogRevision=value.revision;if(automatic){if(state.mode==="collections"){const searchOpen=!$("#search-panel").hidden,q=$("#query").value,focused=document.activeElement?.dataset?.store;renderHome();$("#search-panel").hidden=!searchOpen;$("#search-toggle").setAttribute("aria-expanded",String(searchOpen));$("#query").value=q;applyFilter();loadCounts(serial);if(focused)document.querySelector('[data-store="'+CSS.escape(focused)+'"]')?.focus({preventScroll:true})}status("Collections updated. Your open reading and working set are kept.")}else await navigate(state,false)}catch(e){status("Collections could not refresh: "+e.message,true)}finally{catalogPollBusy=false}}
$("#refresh").onclick=()=>refreshCatalog();
window.addEventListener("focus",()=>refreshCatalog(true));document.addEventListener("visibilitychange",()=>{if(!document.hidden)refreshCatalog(true)});

$("#search-toggle").onclick=()=>{const open=$("#search-panel").hidden;$("#search-panel").hidden=!open;$("#search-toggle").setAttribute("aria-expanded",String(open));if(open)$("#query").focus()};
$("#query").oninput=e=>{if(state.mode!=="archive"){filter=e.target.value.trim().toLowerCase();applyFilter()}};
$("#search-panel").onsubmit=async e=>{e.preventDefault();if(state.mode!=="archive")return;const query=$("#query").value.trim();if(!query){navigate({mode:"archive",id:state.id});return}const n=serial;try{const r=await api("archive-search",{id:state.id,query},controller.signal);if(n!==serial)return;data={...r,total:r.hits.length,offset:0,next_offset:null};state={...state,document:{search:true}};renderArchive();$("#heading").textContent="Search results · "+store().name;status(r.hits.length+" matching messages (up to 100). Clear search to browse titles.")}catch(err){if(err.name!=="AbortError")status(err.message,true)}};
$("#clear-search").onclick=()=>{filter="";$("#query").value="";if(state.mode==="archive")navigate({mode:"archive",id:state.id});else applyFilter()};
$("#working").onclick=()=>{renderWorking();$("#working-dialog").showModal()};$("#close-working").onclick=()=>$("#working-dialog").close();
function packetText(){return ($("#task").value.trim()||"Help me use the following material.")+"\n\n"+selection.map(s=>"From "+s.source+" — "+s.title+"\nOriginal: "+(s.location?s.location+"/":"")+s.path+"\nCollected: "+(s.collectedAt||"this reading session")+"\n"+(s.text||"[Image: open the original file]")).join("\n\n---\n\n")}
$("#copy-request").onclick=async()=>{$("#copy-status").textContent=await copy(packetText())?"Copied. Paste this into your chat with Nova.":"Copy unavailable. Download the reading packet instead."};
$("#save-packet").onclick=()=>{const blob=new Blob([packetText()],{type:"text/markdown;charset=utf-8"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="Nova reading packet.md";a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);$("#copy-status").textContent="Reading packet downloaded with your task, selected passages and original locations."};

window.onpopstate=e=>navigate(e.state||{mode:"collections"},false);
(async()=>{try{const r=await fetch("/api/session",{method:token?"POST":"GET",headers:token?{"X-Desk-Token":token}:{},cache:"no-store"});if(!r.ok)throw Error("Reopen Knowledge Desk from its launcher to reconnect this local session.");const initial=await api("catalog");catalog=initial.stores;catalogRevision=initial.revision;catalogRefreshReady=true;await navigate({mode:"collections"},false);setInterval(()=>refreshCatalog(true),15000)}catch(e){$("#results").innerHTML='<section class="empty"><h3>Reconnect Knowledge Desk</h3><p>'+esc(e.message)+'</p></section>';status(e.message,true)}})();

