'use strict';
const $ = s => document.querySelector(s), esc = s => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let estate, row, draft, view = 'bridge', dirty = false;
const now = () => new Date().toISOString().replace(/\.\d{3}Z$/, 'Z');
function notice(text, error=false) { $('#notice').textContent=text; $('#notice').classList.toggle('error', error); }
function download(value, name) { const a=document.createElement('a'), url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)+'\n'],{type:'application/json'}));a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000); }
async function write(value) { const r=await fetch('/api/write',{method:'POST',headers:{'Content-Type':'application/json','X-Workspace-Token':estate.token},body:JSON.stringify(value)});const data=await r.json();if(!r.ok)throw Error(data.error);return data; }
function capture() { if(!draft)return;document.querySelectorAll('[data-path]').forEach(el=>{const parts=el.dataset.path.split('.');let obj=draft;parts.slice(0,-1).forEach(key=>obj=obj[key]);obj[parts.at(-1)]=el.value;});if(view==='record'&&$('#raw'))draft=JSON.parse($('#raw').value); }
function markDirty() { dirty=true; $('#save').textContent='Save changes'; notice('Unsaved draft · save to update the native record, or export to keep a separate copy.'); }
async function load(select) { const r=await fetch('/api/state');if(!r.ok)throw Error('Could not read the project estate. Retry Refresh.');estate=await r.json();$('#home').textContent=estate.home;$('#count').textContent=estate.projects.length;list();if(select||row){const match=estate.projects.find(x=>x.project_id===(select||row.project_id));if(match)choose(match);else choose(null);}else if(estate.projects.length)choose(estate.projects.find(x=>x.record.project.status==='active')||estate.projects[0]);notice(estate.diagnostics.length?'Some records could not be read: '+estate.diagnostics.map(x=>x.message).join('; '):'Native records loaded · completion and authority stay evidence-bound.',!!estate.diagnostics.length); }
function list() { const q=$('#search').value.toLowerCase();$('#projects').innerHTML=estate.projects.filter(x=>JSON.stringify(x.record.project).toLowerCase().includes(q)).map(x=>`<button data-project="${esc(x.project_id)}" aria-current="${row?.project_id===x.project_id?'page':'false'}"><span class="project-id">${esc(x.project_id)}</span><strong>${esc(x.project_name)}</strong><span>${esc(x.record.project.status)} · ${esc(x.record.project.owner)}</span></button>`).join('')||'<p>No matching project. Clear search or create one.</p>';$('#projects').querySelectorAll('button').forEach(b=>b.onclick=()=>{if(dirty&&!confirm('Discard unsaved changes? Export first if you want a separate copy.'))return;choose(estate.projects.find(x=>x.project_id===b.dataset.project));}); }
function choose(value) {$('#toggle-projects').setAttribute('aria-expanded','false');$('.portfolio').classList.remove('expanded');row=value;draft=value?structuredClone(value.record):null;dirty=false;selectedRoute=null;$('#project').hidden=!value;$('#empty').hidden=!!value;list();if(value)render();}
function input(label,path,value,area=false){return area?`<label>${esc(label)}<textarea data-path="${path}" rows="3">${esc(value)}</textarea></label>`:`<label>${esc(label)}<input data-path="${path}" value="${esc(value)}"></label>`;}
function rows(items, fn, empty){return items?.length?items.map(fn).join(''):`<p class="muted">${empty}</p>`;}
function render(){document.body.dataset.view=view;const p=draft.project;$('#identity').textContent=p.id;$('#title').textContent=p.name;$('#owner').textContent=p.owner+' · updated '+p.updated_at;$('#outcome').textContent=p.outcome;$('#save').textContent=dirty?'Save changes':'Save project';const statuses=draft.completion_contract.states;$('#readings').innerHTML=`<div><small>POSTURE</small><strong>${esc(draft.current.posture)}</strong></div><div><small>OPEN CONTROLS</small><strong>${draft.controls.filter(x=>!['resolved','invalidated'].includes(x.status)).length}</strong></div><div><small>DELIVERY STATES</small><strong>${statuses.filter(x=>x.status==='satisfied').length} / ${statuses.length}</strong></div>`;$('#record-note').textContent=row.path+' · '+row.errors.length+' structural errors · '+row.warnings.length+' cautions. A structural pass does not certify delivery.';document.querySelectorAll('[data-view]').forEach(x=>x.setAttribute('aria-pressed',x.dataset.view===view));
 if(view==='bridge'){
  const active=draft.controls.filter(x=>!['resolved','invalidated'].includes(x.status));
  const attention=active.filter(x=>['issue','dependency','risk'].includes(x.kind)).slice(0,3);
  const current=draft.current;
  const signal=`<section class="situation"><div class="situation-main"><span class="eyebrow">CURRENT POSTURE / ${esc(current.as_of||'DATE NOT SUPPLIED')}</span><div class="situation-line"><h2>${esc(current.posture)}</h2><span class="situation-path">${esc(current.path.join(' / ')||'No current path supplied')}</span></div><p class="situation-move">${esc(current.next_action||'No next action supplied.')}</p><p class="situation-why">${esc(current.purpose_connection||'No purpose connection supplied.')}</p></div><div class="situation-decision"><span class="eyebrow">NEXT CONSEQUENTIAL DECISION</span><p>${esc(current.next_decision||'No decision recorded.')}</p><div class="situation-facts"><span><strong>${active.length}</strong> open controls</span><span><strong>${statuses.filter(x=>x.status==='satisfied').length}/${statuses.length}</strong> delivery states</span></div></div></section>`;
  const constraints=`<section class="attention-band"><div><span class="eyebrow">WATCH THE CONSTRAINT</span><h2>${esc(draft.capacity.bottleneck||'No bottleneck supplied')}</h2><p>Capacity declaration · WIP ${esc(draft.capacity.active_wip)} / ${esc(draft.capacity.wip_limit)}</p></div><div class="attention-items">${attention.length?attention.map(c=>`<details><summary><span class="status-tag open">${esc(c.kind)}</span> ${esc(c.description)}</summary><p>${esc(c.cause_event_effect||'')}</p><p>${esc(c.next_action||'No next action supplied.')}</p><small>Owner ${esc(c.owner||'unsupplied')} · Trigger ${esc(c.trigger||'unsupplied')}</small></details>`).join(''):'<p>No live risk, issue or dependency recorded.</p>'}</div></section>`;
  $('#view').innerHTML=signal+routeProof(draft)+constraints+`<section class="working-notes"><div class="next"><span class="eyebrow">STEER THE PROJECT</span><h2>Set the next owned move</h2>${input('Next action','current.next_action',current.next_action,true)}${input('Purpose connection','current.purpose_connection',current.purpose_connection,true)}<label>Project status<select data-path="project.status">${['proposed','active','paused','recovering','closing','closed','cancelled'].map(s=>`<option ${p.status===s?'selected':''}>${s}</option>`).join('')}</select></label><p class="quiet">Editing a status records a declaration; it does not authorize work or certify completion.</p></div><div class="completion"><span class="eyebrow">COMPLETION CONTRACT</span><h2>What still needs proof</h2>${rows(statuses,s=>`<div class="state-row"><span class="status-tag ${s.status==='satisfied'?'done':'open'}">${esc(s.status)}</span><strong>${esc(s.name)}</strong><small>${esc(s.evidence_ids.join(', ')||'No evidence linked')}</small></div>`,'No contract states recorded.')}</div></section>`;
 }
 if(view==='route')$('#view').innerHTML=routeProof(draft)+`<div class="route-grid"><section class="panel route"><span class="eyebrow">OUTCOME HIERARCHY</span><h2>The delivery route.</h2>${rows(draft.hierarchy,h=>`<div class="route-node ${h.parent_id?'child':''}"><span class="node-id">${esc(h.id)}</span><div><h3>${esc(h.label)}</h3><p>${esc(h.purpose)}</p><small>${esc(h.kind)} · ${esc(h.status)} · ${esc(h.parent_id||'Root')}</small></div></div>`,'No hierarchy recorded.')}</section><section class="panel queue"><span class="eyebrow">WORK PACKAGES</span>${rows(draft.work_packages,(w,i)=>`<details open><summary>${esc(w.id)} · ${esc(w.outcome)}</summary><label>Status<select data-path="work_packages.${i}.status">${['planned','ready','active','blocked','complete','cancelled'].map(s=>`<option ${w.status===s?'selected':''}>${s}</option>`).join('')}</select></label>${input('Next action',`work_packages.${i}.next_action`,w.next_action,true)}<small>Owner ${esc(w.owner)} · Depends on ${esc(w.dependency_ids.join(', ')||'none')} · Criteria ${esc(w.acceptance_criteria_ids.join(', '))}</small></details>`,'No work packages.')}</section></div><section class="panel"><h2>Acceptance criteria</h2>${rows(draft.exit_criteria,e=>`<p><strong>${esc(e.id)}</strong> · ${esc(e.description)} <span class="status">${esc(e.status)}</span><small>${esc(e.evidence_ids.join(', ')||'No evidence linked')}</small></p>`,'No criteria recorded.')}<p>Use Control record for new milestones, dependencies and authority links. The native validator checks all references on save.</p></section>`;
 if(view==='ledger')$('#view').innerHTML=`<div class="ledger-grid"><section class="panel"><span class="eyebrow">DECISION LEDGER</span><h2>What changed, and why?</h2>${rows(draft.decisions,d=>`<details><summary>${esc(d.id)} · ${esc(d.question||d.decision||d.description||'Decision')} · ${esc(d.status)}</summary><pre>${esc(JSON.stringify(d,null,2))}</pre></details>`,'No decisions recorded. Add a fully attributed decision in Control record.')}${rows(draft.source_authority,s=>`<p class="source"><strong>${esc(s.kind)}</strong><span>${esc(s.locator)}</span><small>${esc(s.status)} · ${esc(s.scope)}</small></p>`,'No source authority.')}</section><section class="panel"><span class="eyebrow">EVIDENCE REGISTER</span><h2>What have we actually seen?</h2>${rows(draft.evidence,e=>`<details><summary>${esc(e.id)} · ${esc(e.level)} · ${esc(e.claim||e.description||'Evidence')}</summary><pre>${esc(JSON.stringify(e,null,2))}</pre></details>`,'No evidence recorded. Absence is shown rather than replaced with a progress estimate.')}</section></div>`;
 if(view==='record')$('#view').innerHTML=`<section class="panel"><span class="eyebrow">NATIVE CONTROL · ADVANCED EDITOR</span><h2>The complete project record.</h2><p>All sections and unknown extension fields remain intact. Saves run the native schema and reference validator; the previous record is retained in bridge-history. Completion states require the native evidence rules.</p><label>Project-control JSON<textarea id="raw" rows="28" spellcheck="false">${esc(JSON.stringify(draft,null,2))}</textarea></label><details><summary>Structural cautions</summary><pre>${esc(JSON.stringify({errors:row.errors,warnings:row.warnings},null,2))}</pre></details></section>`;
 if(view==='route')$('#view').insertAdjacentHTML('afterbegin','<div class="project-actions"><button id="add-milestone">Add milestone</button><button id="add-work">Add work package</button></div>');
 if(view==='ledger')$('#view').insertAdjacentHTML('afterbegin','<div class="project-actions"><button id="add-decision">Record decision</button><button id="add-evidence">Record evidence</button></div>');
 const addButtons={'#add-milestone':'milestone','#add-work':'work','#add-decision':'decision','#add-evidence':'evidence'};
 for(const [selector,kind] of Object.entries(addButtons))if($(selector))$(selector).onclick=()=>addEntry(kind);
 document.querySelectorAll('[data-route]').forEach(el=>el.onclick=()=>{try{capture();selectedRoute=el.dataset.route;render();}catch(e){notice(e.message,true);}});
 document.querySelectorAll('[data-route-scope]').forEach(el=>el.onclick=()=>{try{capture();routeScope=el.dataset.routeScope;render();}catch(e){notice(e.message,true);}});
 document.querySelectorAll('[data-path],#raw').forEach(el=>el.oninput=markDirty);
}
const entryDialog=document.createElement('dialog');entryDialog.id='entry-dialog';document.body.append(entryDialog);
function addEntry(kind){
 try{capture();}catch(e){notice(e.message,true);return;}
 const text=(name,label,area=false)=>`<label>${label}<${area?'textarea rows="3"':'input'} name="${name}" required>${area?'</textarea>':''}</label>`;
 const select=(name,label,items)=>`<label>${label}<select name="${name}">${items.map(x=>`<option value="${esc(x.id)}">${esc(x.label||x.id)}</option>`).join('')}</select></label>`;
 let fields='';
 if(kind==='milestone')fields=text('label','Milestone name')+text('purpose','Outcome / purpose',true)+select('parent','Parent phase / workstream',draft.hierarchy)+text('criterion','Acceptance criterion',true);
 if(kind==='work')fields=text('outcome','Work-package outcome',true)+select('parent','Parent milestone / workstream',draft.hierarchy)+text('owner','Owner')+text('next','Next action',true)+text('criterion','Acceptance criterion',true)+select('authority','Authority grant',draft.authority.grants);
 if(kind==='decision')fields=text('decision','Decision / proposal',true)+text('rationale','Rationale',true)+text('options','Options considered (one per line)',true)+text('authority','Decision owner / authority')+select('source','Authority source',draft.source_authority)+'<label>Status<select name="status"><option>proposed</option><option>accepted</option><option>rejected</option></select></label>';
 if(kind==='evidence')fields=text('claim','Claim supported',true)+text('locator','Evidence locator')+text('method','How was it checked?',true)+text('limits','What remains unproven?',true)+text('actor','Observer / reporter')+'<label>Evidence level<select name="level"><option>reported</option><option>observed</option><option>verified</option><option>accepted</option><option>proposed</option><option>rejected</option></select></label>';
 entryDialog.innerHTML=`<form><div class="section-title"><h2>Add ${kind}</h2><button type="button" class="cancel">Cancel</button></div>${fields}<button class="primary">Add to draft</button><p>This changes your draft. Save project to validate and persist it.</p></form>`;
 entryDialog.querySelector('.cancel').onclick=()=>entryDialog.close();
 entryDialog.querySelector('form').onsubmit=e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target)), suffix=Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,5);const id=(prefix)=>prefix+'-'+suffix;
  if(kind==='milestone'){const mid=id('M'),ec=id('EC');draft.hierarchy.push({id:mid,kind:'milestone',label:f.label,parent_id:f.parent,status:'planned',purpose:f.purpose,exit_criteria_ids:[ec]});draft.exit_criteria.push({id:ec,owner_id:mid,description:f.criterion,status:'pending',evidence_ids:[],waiver_decision_id:null});}
  if(kind==='work'){const wid=id('WP'),ec=id('EC');draft.work_packages.push({id:wid,parent_id:f.parent,outcome:f.outcome,status:'planned',dependency_ids:[],acceptance_criteria_ids:[ec],authority_ids:[f.authority],owner:f.owner,next_action:f.next});draft.exit_criteria.push({id:ec,owner_id:wid,description:f.criterion,status:'pending',evidence_ids:[],waiver_decision_id:null});draft.capacity.queue.push(wid);}
  if(kind==='decision')draft.decisions.push({id:id('DEC'),status:f.status,decision:f.decision,options:f.options.split('\n').filter(Boolean),rationale:f.rationale,authority:f.authority,source_id:f.source,date:now(),supersedes_ids:[]});
  if(kind==='evidence')draft.evidence.push({id:id('EVID'),claim:f.claim,level:f.level,locator:f.locator,observed_at:now(),method:f.method,limits:f.limits,actor:f.actor});
  markDirty();entryDialog.close();render();notice('Added to draft. Save project to validate references and persist.');};entryDialog.showModal();
}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{try{capture();view=b.dataset.view;render();}catch(e){notice('Invalid JSON draft: '+e.message,true);}});
$('#search').oninput=()=>estate&&list();
$('#toggle-projects').onclick=()=>{const open=$('.portfolio').classList.toggle('expanded');$('#toggle-projects').setAttribute('aria-expanded',String(open));if(open)$('#search').focus();};
$('#refresh').onclick=()=>{if(!dirty||confirm('Discard unsaved draft and reload native records?'))load().catch(e=>notice(e.message,true));};
$('#save').onclick=async()=>{try{capture();await write({action:'save',id:row.project_id,expected:row.fingerprint,record:draft});await load(row.project_id);notice('Saved the native control. Previous content retained in bridge-history.');}catch(e){notice(e.message,true);}};
$('#export').onclick=()=>{try{capture();download(draft,`${row.project_id}-project-control.json`);}catch(e){notice(e.message,true);}};
function newProject(){ if(dirty&&!confirm('Discard unsaved changes? Export first if you want a separate copy.'))return;$('#create-error').textContent='';$('#create-dialog').showModal(); }
$('#new').onclick=$('#empty-new').onclick=newProject;$('#cancel-create').onclick=()=>$('#create-dialog').close();
$('#create-form').onsubmit=async e=>{e.preventDefault();try{const result=await write({action:'create',...Object.fromEntries(new FormData(e.target))});$('#create-dialog').close();e.target.reset();await load(result.id);notice(result.created?'Project proposal created.':'Existing project reopened.');}catch(err){$('#create-error').textContent=err.message;}};
$('#import').onchange=async e=>{try{if(dirty&&!confirm('Discard unsaved draft and import another project?'))return;const record=JSON.parse(await e.target.files[0].text());const r=await write({action:'import',record});await load(r.id);notice('Imported valid native control; supplied JSON preserved in the estate imports folder.');}catch(err){notice(err.message,true);}finally{e.target.value='';}};
const skin=localStorage.getItem('dennis-skin')||'bridge';$('#skin').value=['bridge','folio','redline'].includes(skin)?skin:'bridge';document.body.dataset.skin=$('#skin').value;
$('#skin').onchange=e=>{document.body.dataset.skin=e.target.value;localStorage.setItem('dennis-skin',e.target.value);};
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});load().catch(e=>notice(e.message,true));
