'use strict';
let selectedRoute=null, routeScope='attention';
const stationName=n=>n.label||n.outcome||n.id;
function routeProof(r){
 const nodes=r.hierarchy||[], work=r.work_packages||[], all=[...nodes,...work];
 if(!selectedRoute || !all.some(x=>x.id===selectedRoute)) selectedRoute=r.current?.active_commitment_id||[...(r.current?.path||[])].reverse().find(id=>all.some(x=>x.id===id))||work.find(x=>['active','blocked','ready'].includes(x.status))?.id||nodes[0]?.id||null;
 const item=all.find(x=>x.id===selectedRoute);
 const children=id=>nodes.filter(x=>x.parent_id===id).concat(work.filter(x=>x.parent_id===id));
 const proofFor=x=>{const criteria=(r.exit_criteria||[]).filter(c=>c.owner_id===x.id||(x.acceptance_criteria_ids||x.exit_criteria_ids||[]).includes(c.id));const ids=new Set(criteria.flatMap(c=>c.evidence_ids||[]));return {criteria,evidence:(r.evidence||[]).filter(e=>ids.has(e.id))};};
 const statusClass=s=>['blocked','rejected','invalidated'].includes(s)?'bad':['complete','satisfied','accepted','resolved'].includes(s)?'done':['active','ready','observed','verified'].includes(s)?'live':'open';
 function station(n,depth=0){const pf=proofFor(n), count=pf.criteria.filter(c=>c.status==='satisfied').length;return `<button class="route-station ${n.kind||'work'} ${statusClass(n.status)} ${selectedRoute===n.id?'selected':''} depth-${Math.min(depth,5)}" data-route="${esc(n.id)}" aria-current="${selectedRoute===n.id?'step':'false'}"><span class="station-mark" aria-hidden="true"></span><span class="station-copy"><small>${esc(n.kind||'work')} / ${esc(n.id)}</small><strong>${esc(stationName(n))}</strong><span>${esc(n.purpose||n.next_action||'No next action supplied')}</span></span><span class="station-meta"><em>${esc(n.status)}</em>${pf.criteria.length?`<small>${count}/${pf.criteria.length} criteria</small>`:''}</span></button>`;}
 function descendants(parent,depth=1,visited=new Set()){if(visited.has(parent))return '';const next=new Set(visited);next.add(parent);return children(parent).filter(n=>n.kind||routeScope==='all'||n.status!=='complete'||n.id===selectedRoute).map(n=>station(n,depth)+descendants(n.id,depth+1,next)).join('');}
 const roots=nodes.filter(n=>!n.parent_id||!nodes.some(p=>p.id===n.parent_id));
 const groups=roots.map((root,i)=>`<section class="route-phase" id="phase-${i}"><div class="phase-gutter"><span>${String(i+1).padStart(2,'0')}</span><small>${esc(root.kind)}</small></div><div class="phase-content">${station(root)}${descendants(root.id)}</div></section>`).join('');
 const orphans=work.filter(w=>!all.some(n=>n.id===w.parent_id)).filter(w=>routeScope==='all'||w.status!=='complete'||w.id===selectedRoute).map(w=>station(w)).join('');
 const hidden=routeScope==='attention'?work.filter(w=>w.status==='complete'&&w.id!==selectedRoute).length:0;
 const {criteria,evidence}=item?proofFor(item):{criteria:[],evidence:[]};
 const deps=item?.dependency_ids||[];
 const path=[];let walk=item,seen=new Set();while(walk&&!seen.has(walk.id)){path.unshift(walk);seen.add(walk.id);walk=all.find(x=>x.id===walk.parent_id);}
 let inspector='<h3>Choose a commitment</h3><p>Select a station to see its place, dependencies and completion proof.</p>';
 if(item)inspector=`<div class="inspector-top"><span class="eyebrow">SELECTED COMMITMENT</span><span class="status-tag ${statusClass(item.status)}">${esc(item.status)}</span></div><h3>${esc(stationName(item))}</h3><p class="inspector-purpose">${esc(item.purpose||item.next_action||'No next action supplied')}</p><div class="inspector-section"><span class="eyebrow">PLACE IN THE ROUTE</span><p class="breadcrumbs">${path.map(x=>esc(stationName(x))).join(' <span aria-hidden="true">›</span> ')}</p><small>${esc(item.owner||'No station owner supplied')}</small></div>${item.next_action?`<div class="inspector-section"><span class="eyebrow">NEXT ACTION</span><p>${esc(item.next_action)}</p></div>`:''}<div class="inspector-section"><span class="eyebrow">DEPENDENCIES</span>${deps.length?deps.map(id=>{const dep=all.find(x=>x.id===id);return `<button class="dependency-link" data-route="${esc(id)}">${esc(dep?stationName(dep):id)} <span>${esc(dep?.status||'reference')}</span></button>`;}).join(''):'<p class="quiet">No dependencies supplied.</p>'}</div><div class="inspector-section"><span class="eyebrow">ACCEPTANCE</span>${criteria.length?criteria.map(c=>`<div class="proof-item"><span class="status-tag ${statusClass(c.status)}">${esc(c.status)}</span><p>${esc(c.description)}</p><small>${esc((c.evidence_ids||[]).join(', ')||'No evidence linked')}</small></div>`).join(''):'<p class="quiet">No criteria linked.</p>'}</div><div class="inspector-section"><span class="eyebrow">LINKED EVIDENCE</span>${evidence.length?evidence.map(e=>`<div class="proof-item"><strong>${esc(e.level)} · ${esc(e.id)}</strong><p>${esc(e.claim||e.description||'')}</p><small>${esc(e.locator||'No locator supplied')}</small></div>`).join(''):'<p class="quiet">No supporting evidence linked.</p>'}</div><details class="native-record"><summary>Inspect native station record</summary><pre>${esc(JSON.stringify(item,null,2))}</pre></details>`;
 return `<section class="route-artifact"><div class="route-head"><div><span class="eyebrow">DELIVERY TOPOLOGY</span><h2>The route to the outcome</h2><p>Native parentage and record order. Position implies neither elapsed time nor percent complete.</p></div><div class="route-tools"><button class="scope-button" data-route-scope="${routeScope==='all'?'attention':'all'}" aria-pressed="${routeScope==='all'}">${routeScope==='all'?'Show live route':`Show all stations${hidden?' · '+hidden+' declared complete':''}`}</button><div class="route-key"><span><i class="key-live"></i> Active / ready</span><span><i class="key-done"></i> Declared complete</span><span><i class="key-open"></i> Other</span></div></div></div><div class="route-proof-grid"><div class="route-map" aria-label="Project route">${groups||'<p>No hierarchy recorded.</p>'}${orphans?`<section class="route-phase unplaced"><div class="phase-gutter"><span>—</span><small>Unplaced</small></div><div class="phase-content">${orphans}</div></section>`:''}</div><aside class="route-inspector" aria-label="Selected commitment details">${inspector}</aside></div></section>`;
}
